// Necesitamos configurar un pipeline que clone el repositorio 5etools,
// contruya en k8s y que de manera automática actualice el despliegue en k8s.
//Cada vez que haya un cambio en el repositorio, el pipeline debe actualizar el despliegue.
//Primero vamos a hacerlo con docker run
//Despues, vamos a a autmoatizar el despliegue en cuanto se haga un commit al repositorio

pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/ikdxz/5etools_InakiSpinardi.git'
        LOCAL_REPO = '5etools-src'
        IMAGE_NAME = 'inaki/5etools:latest'
        KUBECONFIG = '/var/jenkins_home/.kube/config'

    }



    stages {

        stage('Clonar repositorio') {
            steps {
                sh '''
                    if [ -d "$LOCAL_REPO" ]; then
                        cd $LOCAL_REPO
                    else
                        git clone $REPO_URL
                    fi
                '''
            }
        }
        stage('Construir imagen Docker') {
            steps {
                sh '''
                    cd $LOCAL_REPO
                    mv ../Dockerfile . 
                    docker build -t $IMAGE_NAME .
                '''
            }
        }
stage('Desplegar en Kubernetes') {
    steps {
        withCredentials([string(credentialsId: 'K8S_TOKEN', variable: 'TOKEN')]) {
            sh '''
                # Generar kubeconfig temporal
cat <<EOF > kubeconfig.yaml
apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://host.docker.internal:6443
  name: k8s-cluster
contexts:
- context:
    cluster: k8s-cluster
    user: jenkins
  name: jenkins-context
current-context: jenkins-context
users:
- name: jenkins
  user:
    token: $TOKEN
EOF

                export KUBECONFIG=$(pwd)/kubeconfig.yaml
                kubectl set image deployment/5etools-deployment 5etools-container=$IMAGE_NAME --record
            '''
        }
    }
}


}
